apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo
    environment: lab
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"